# Generated by Django 4.0.3 on 2022-04-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('seats', models.IntegerField(default=None, max_length=200)),
                ('style', models.CharField(default=None, max_length=200)),
                ('price', models.FloatField(default=None, max_length=200)),
                ('saleOff', models.FloatField(default=None, max_length=200)),
                ('addedDate', models.DateTimeField()),
                ('note', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
    ]
